// Temporary flat config generated by SunLint
import customPlugin from 'C:\Users\ADMIN\AppData\Roaming\npm\node_modules\@sun-asterisk\sunlint\integrations\eslint\plugin\index.js';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';

export default [
  {
  "files": [
    "**/*.js",
    "**/*.jsx",
    "**/*.ts",
    "**/*.tsx"
  ],
  "languageOptions": {
    "ecmaVersion": "latest",
    "sourceType": "module",
    "parserOptions": {
      "ecmaFeatures": {
        "jsx": true
      }
    }
  },
  "plugins": { "custom": customPlugin, "react": reactPlugin, "react-hooks": reactHooksPlugin },
    "rules": {
    "react/no-this-in-sfc": "warn",
    "no-param-reassign": "warn",
    "react/function-component-definition": "warn",
    "react/forbid-component-props": "warn",
    "react-hooks/rules-of-hooks": "warn",
    "react-hooks/exhaustive-deps": "warn",
    "react/no-did-mount-set-state": "warn",
    "react/no-did-update-set-state": "warn",
    "react/no-direct-mutation-state": "warn",
    "react/jsx-no-constructed-context-values": "warn",
    "react/forbid-dom-props": "warn"
  }
},
  {
    files: ['**/*.ts', '**/*.tsx'],
    plugins: { "custom": customPlugin, "react": reactPlugin, "react-hooks": reactHooksPlugin },
    languageOptions: {
      parser: (await import('@typescript-eslint/parser')).default,
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true
        }
      }
    },
    rules: {
  "react/no-this-in-sfc": "warn",
  "no-param-reassign": "warn",
  "react/function-component-definition": "warn",
  "react/forbid-component-props": "warn",
  "react-hooks/rules-of-hooks": "warn",
  "react-hooks/exhaustive-deps": "warn",
  "react/no-did-mount-set-state": "warn",
  "react/no-did-update-set-state": "warn",
  "react/no-direct-mutation-state": "warn",
  "react/jsx-no-constructed-context-values": "warn",
  "react/forbid-dom-props": "warn"
}
  }
];
